#!/bin/bash
VIP=172.17.14.161
function start() {
    ifconfig lo:0 $VIP netmask 255.255.255.255 broadcast $VIP
    echo 1 >/proc/sys/net/ipv4/conf/lo/arp_ignore
    echo 2 >/proc/sys/net/ipv4/conf/lo/arp_announce
    echo 1 >/proc/sys/net/ipv4/conf/all/arp_ignore
    echo 2 >/proc/sys/net/ipv4/conf/all/arp_announce
    echo “Real Server $(uname -n) started”
}
function stop() {
    ifconfig lo:0 down
    ifconfig lo:0 $VIP netmask 255.255.255.255 broadcast $VIP
    echo 0 >/proc/sys/net/ipv4/conf/lo/arp_ignore
    echo 0 >/proc/sys/net/ipv4/conf/lo/arp_announce
    echo 0 >/proc/sys/net/ipv4/conf/all/arp_ignore
    echo 0 >/proc/sys/net/ipv4/conf/all/arp_announce
    echo “Real Server $(uname -n) stopped”
}
case $1 in
    start)
        start
    ;;
    stop)
        stop
    ;;
    *)
        echo “Usage: $0 {start|stop}”
        exit 1
esac